version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=unico
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/database/data
      - ./db/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql

  markets:
    restart: unless-stopped
    build: .
    ports:
      - 3333:3333
    environment: 
      - GO_ENV=staging
      - LOGG_LEVEL=Info
      - GIN_MODE=release
    depends_on:
      - postgres