version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=unico
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/database/data
      - ./db/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql