// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateMarket struct {
	Long       int    `json:"long"`
	Lat        int    `json:"lat"`
	Setcens    string `json:"setcens"`
	Areap      string `json:"areap"`
	Coddist    int    `json:"coddist"`
	Distrito   string `json:"distrito"`
	Codsubpref int    `json:"codsubpref"`
	Subpref    string `json:"subpref"`
	Regiao5    string `json:"regiao5"`
	Regiao8    string `json:"regiao8"`
	NomeFeira  string `json:"nomeFeira"`
	Registro   string `json:"registro"`
	Logradouro string `json:"logradouro"`
	Numero     string `json:"numero"`
	Bairro     string `json:"bairro"`
	Referencia string `json:"referencia"`
}

type Market struct {
	Long       int    `json:"long"`
	Lat        int    `json:"lat"`
	Setcens    string `json:"setcens"`
	Areap      string `json:"areap"`
	Coddist    int    `json:"coddist"`
	Distrito   string `json:"distrito"`
	Codsubpref int    `json:"codsubpref"`
	Subpref    string `json:"subpref"`
	Regiao5    string `json:"regiao5"`
	Regiao8    string `json:"regiao8"`
	NomeFeira  string `json:"nomeFeira"`
	Registro   string `json:"registro"`
	Logradouro string `json:"logradouro"`
	Numero     string `json:"numero"`
	Bairro     string `json:"bairro"`
	Referencia string `json:"referencia"`
}

type MarketFilters struct {
	Long       *int    `json:"long"`
	Lat        *int    `json:"lat"`
	Setcens    *string `json:"setcens"`
	Areap      *string `json:"areap"`
	Coddist    *int    `json:"coddist"`
	Distrito   *string `json:"distrito"`
	Codsubpref *int    `json:"codsubpref"`
	Subpref    *string `json:"subpref"`
	Regiao5    *string `json:"regiao5"`
	Regiao8    *string `json:"regiao8"`
	NomeFeira  *string `json:"nomeFeira"`
	Registro   *string `json:"registro"`
	Logradouro *string `json:"logradouro"`
	Numero     *string `json:"numero"`
	Bairro     *string `json:"bairro"`
	Referencia *string `json:"referencia"`
}

type MarketToUpdate struct {
	Long       *int    `json:"long"`
	Lat        *int    `json:"lat"`
	Setcens    *string `json:"setcens"`
	Areap      *string `json:"areap"`
	Coddist    *int    `json:"coddist"`
	Distrito   *string `json:"distrito"`
	Codsubpref *int    `json:"codsubpref"`
	Subpref    *string `json:"subpref"`
	Regiao5    *string `json:"regiao5"`
	Regiao8    *string `json:"regiao8"`
	NomeFeira  *string `json:"nomeFeira"`
	Registro   string  `json:"registro"`
	Logradouro *string `json:"logradouro"`
	Numero     *string `json:"numero"`
	Bairro     *string `json:"bairro"`
	Referencia *string `json:"referencia"`
}
