name: sonar
on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  sonar:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      
      - name: Install dependencies
        run:
          go mod download

      - name: Test and coverage
        run: GO_ENV=development go test ./... -race -coverprofile=coverage.out -json > report.json
      
      - name: Go Vet 
        run: go vet ./... 2> govet-report.out
        
      - name: Go Lint
        run: |
          go get -u -v golang.org/x/lint/golint
          go install -v golang.org/x/lint/golint
          golint ./... > golint-report.out

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}